pipeline:
  name: Trigger
  identifier: Trigger
  projectIdentifier: DotNetPipeline
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1704192628541
        repoName: anujrajkumar/Demo
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Check
                  identifier: Check
                  spec:
                    shell: Sh
                    command: |-
                      ls -ltr
                      chmod 777 hello.sh
                      ./hello.sh
                      chmod 777 echo
                      ./echo

                      echo "<+stage.variables.hello>"
                      echo "<+stage.variables.bye>"
                      echo "<+stage.variables.tata>"
                      echo "<+trigger.event>"
                      echo "<+pipeline.triggerType>"
              - step:
                  type: Run
                  name: test
                  identifier: test
                  spec:
                    shell: Sh
                    command: |-
                      echo "trigger manually"
                      echo "<+pipeline.triggerType>"
                  when:
                    stageStatus: Success
                    condition: <+pipeline.triggerType> == "MANUAL"
        variables:
          - name: hello
            type: String
            description: ""
            required: true
            value: <+input>
          - name: tata
            type: String
            description: ""
            required: true
            value: <+input>
          - name: bye
            type: String
            description: ""
            required: false
            value: <+input>
